<?php

/**
 * Created by JiangJiaCai.
 * User: LongBob
 * Date: 17-4-11
 * Time: 下午10:50
 */
use FastD\Annotation\Map as Map;

class AnnotationMapTest extends PHPUnit_Framework_TestCase
{

    /**
     * @Map
     */
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }
}